version: '3.6'

networks:
  metrics_net:
    driver: 'bridge'

services:
  server:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: go run cmd/server/main.go
    volumes:
      - ../:/app
    environment:
      ADDRESS: '0.0.0.0:8080'
      LOG_LEVEL: "info"
      STORE_INTERVAL: 300
      FILE_STORAGE_PATH: '/tmp/metrics-db.json'
      RESTORE: true
#      DATABASE_DSN: 'postgres://user:password@db/db-go-yandex-metrics'
    networks:
      - metrics_net
    depends_on:
      - db

#  agent:
#    build:
#      context: ./../
#      dockerfile: ./docker/Dockerfile
##    restart: unless-stopped
#    command: go run cmd/agent/main.go
#    volumes:
#      - ../:/app
#    environment:
#      ADDRESS: "server:8080"
#      REPORT_INTERVAL: 4
#      POLL_INTERVAL: 3
#    networks:
#      - metrics_net
#    depends_on:
#      - db
  db:
    container_name: db
#    image: postgres:15-alpine
    image: postgres:10.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5464:5432
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    networks:
      - metrics_net


